---
- name: Download chain script
  get_url:
    url: "https://s3.amazonaws.com/misc-temp-files/download-kovan.sh"
    checksum: "sha256:489930b5f8e3ab92cf4bb8d00fb8f1c17b340a490b6a5265e2ca2d4592f7a918"
    dest: "/home/{{ ansible_user }}/download-kovan.sh"

- name: Run chain script
  args:
    creates: 'kovan-chain-downloaded'
  command: 'tmux new -d -s kovan "sudo bash download-kovan.sh bootnode >kovan.log 2>&1"'
